const C = {
  INIT_STEP: "INIT_STEP",
  NEXT_STEP: "NEXT_STEP",
  GO_NEXT_AUTO: "GO_NEXT_AUTO",
  INIT_BUBBLE: "INIT_BUBBLE",
  ADD_BUBBLE: "ADD_BUBBLE",
  REMOVE_BUBBLE: "REMOVE_BUBBLE",
  CLEAR_BOX: "CLEAR_BOX",
  START_CHAT: "START_CHAT",
  SEND_PW_REQUEST: "SEND_PW_REQUEST",
  GET_PASSWORD: "GET_PASSWORD",
  REDIRECT_PORTFOLIO: "REDIRECT_PORTFOLIO",
  DOWNLOAD_CV: "DOWNLOAD_CV",
  SHOW_CARDS: "SHOW_CARDS",
  SHOW_OPTIONS: "SHOW_OPTIONS",
  DEFAULT_USER_EMAIL: "DEFAULT_USER_EMAIL",
  FETCH_USER_PW: "FETCH_USER_PW",
  RECEIVE_DATA: "RECEIVE_DATA",
  CANCEL_FETCHING: "CANCEL_FETCHING",
  INIT_INDEXARRAY: "INIT_INDEXARRAY",
  CHANGE_OPTION: "CHANGE_OPTION",
  TOGGLE_VISIBLE: "TOGGLE_VISIBLE",
  TOGGLE_LABEL_VISIBLE: "TOGGLE_LABEL_VISIBLE",
  BTN_MOVE: "BTN_MOVE",
  UPDATE_BOX_HEIGHT: "UPDATE_BOX_HEIGHT",
  UPDATE_CONTAINER_HEIGHT: "UPDATE_CONTAINER_HEIGHT",
  UPDATE_SCROLLTOP: "UPDATE_SCROLLTOP"
};

const TESTC = {
  REQUEST_BUBS: "REQUEST_BUBS",
  RECEIVE_BUBS: "RECEIVE_BUBS",
  GET_CUR_USER: "GET_CUR_USER"
};

const CBUB = {
  TEXT_BUBBLE: "TEXT_BUBBLE",
  IMAGE_BUBBLE: "IMAGE_BUBBLE",
  BUTTONGROUP_BUBBLE: "BUTTONGROUP_BUBBLE",
  INPUTPW_BUBBLE: "INPUTPW_BUBBLE",
  CARDS_BUBBLE: "CARDS_BUBBLE"
};

export { C, CBUB, TESTC };
