const constbubtype = {
  TEXT_BUBBLE: "TEXT_BUBBLE",
  IMAGE_BUBBLE: "IMAGE_BUBBLE",
  BUTTONGROUP_BUBBLE: "BUTTONGROUP_BUBBLE",
  INPUTPW_BUBBLE: "INPUTPW_BUBBLE",
  CARD_BUBBLE: "CARD_BUBBLE"
};

export default constbubtype;
